name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Trigger bei Tags wie v1.0.0, v1.2.3

jobs:
  release:
    runs-on: [ self-hosted, richman-gaming ]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Optional: Build your assets here if needed
      # - name: Build project
      #   run: |
      #     npm install
      #     npm run build
      #   # Ersetzen Sie dies durch Ihre tatsächlichen Build-Befehle

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            # Hier können Sie Pfade zu den Assets angeben, die Sie hochladen möchten.
            # Zum Beispiel:
            # dist/my-app.zip
            # build/release-notes.txt
          draft: false # Setzen Sie dies auf true, wenn der Release zuerst als Entwurf erstellt werden soll
          prerelease: false # Setzen Sie dies auf true, wenn es ein Pre-Release ist
          generate_release_notes: true # Generiert automatische Release-Notes basierend auf Commits
          name: Release ${{ github.ref_name }} # Name des Releases (z.B. Release v1.0.0)
          tag_name: ${{ github.ref }} # Der Tag, der den Workflow ausgelöst hat (z.B. v1.0.0)
